name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Testing on Linux'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker://aoyako/boost_app:latest

      - name: 'Update packages'
        run: |
          sudo apt update
          sudo apt install libboost-system-dev libboost-filesystem-dev libboost-program-options-dev -y

      - name: 'Build'
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
    
      - name: 'Test'
        env:
          TESTSUITE: 'testsuite'
          MOCKSERVER: 'mockserver'
          WEATHER_BIN: 'Weather'
          TOKEN_FILE: 'token.txt'
        run: |
          export WORKING_PATH=$(pwd)
          git clone https://gitlab.com/mykhailo.lohachov/ci_storage
          mkdir -p $WORKING_PATH/build/testing
          export TEST_DIR=$WORKING_PATH/build/testing && export PATH=$PATH:$TEST_DIR
          cd ci_storage && git checkout master && cp $TESTSUITE $TEST_DIR && cp $TOKEN_FILE $TEST_DIR && cp $MOCKSERVER $TEST_DIR
          cp $WORKING_PATH/build/$WEATHER_BIN $TEST_DIR
          cd $TEST_DIR
          chmod +x $TESTSUITE
          ./$MOCKSERVER &
          ./$TESTSUITE
