name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Testing on Linux (without aoyako/boost_app docker image)'
    runs-on: ubuntu-latest
    environment: token

    steps:
      - uses: actions/checkout@v3

      - name: 'Update packages'
        run: |
          sudo apt update
          sudo apt install libboost-system-dev libboost-filesystem-dev libboost-program-options-dev -y

      - name: 'Build'
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
    
      - name: 'Test'
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: ./build/Weather -t $TOKEN -c Kyiv
